(()=>{
 'use strict';
 for(const href of ['video-studio.css','video-mentions.css']){const sheet=document.createElement('link');sheet.rel='stylesheet';sheet.href=href;document.head.append(sheet)}
 const nav=document.createElement('button');nav.className='nav-item';nav.dataset.page='video-studio';nav.title='视频生成';nav.setAttribute('aria-label','视频生成');nav.textContent='▷';document.querySelector('aside nav').append(nav);
 const page=document.createElement('section');page.id='video-studio';page.className='page';page.hidden=true;
 page.innerHTML=`<div class="page-heading vs-heading"><div><h2>视频生成</h2><p>从灵感到动态影像 · 独立于画布的创作空间</p></div></div>
 <div class="vs-layout"><section class="vs-panel"><div class="vs-tabs" role="tablist" aria-label="生成模式"><button type="button" role="tab" data-mode="text" aria-selected="true">文生视频</button><button type="button" role="tab" data-mode="frames" aria-selected="false">首尾帧生视频</button><button type="button" role="tab" data-mode="references" aria-selected="false">多图参考生视频</button></div>
 <form class="vs-form"><section id="vs-material-section" hidden><div class="vs-material-title"><b id="vs-material-label">首尾帧</b><button type="button" id="vs-swap">交换首尾帧</button></div><div id="vs-materials" class="vs-materials"></div><p class="vs-muted">支持 PNG、JPEG、WebP · 每张不超过 10 MB</p><div id="vs-unavailable" class="vs-alert" hidden>多图参考暂未接入当前 API。可预览素材配置，暂不能提交；不会将参考图作为首尾帧发送。</div></section>
 <label>提示词<textarea id="vs-prompt" maxlength="10000" required placeholder="描述主体动作、镜头运动和场景变化，例如：镜头缓缓向前推进，晨雾掠过湖面，阳光逐渐照亮远山。"></textarea></label>
 <div class="vs-grid"><label>模型<select id="vs-model"><option>H3</option></select></label><label>时长<select id="vs-duration">${Array.from({length:15},(_,i)=>`<option value="${i+1}" ${i===4?'selected':''}>${i+1} 秒</option>`).join('')}</select></label><label>画面比例<select id="vs-ratio"><option>16:9</option><option>9:16</option><option>4:3</option><option>1:1</option></select></label><label>分辨率<select id="vs-resolution"><option>480p</option><option>576p</option><option>768p</option></select></label></div>
 <details><summary>参数说明</summary><p>分辨率为画面短边；时长按模型帧数规则对齐。每次生成一个视频。当前接口需要填写提示词，不支持的参数不作展示。</p></details><button class="primary vs-submit" id="vs-submit">生成视频</button><p id="vs-form-message" class="vs-message" role="alert"></p></form></section>
 <section class="vs-panel"><div class="vs-preview-heading"><h3>生成预览</h3><span id="vs-status" class="vs-status">等待生成</span></div><div class="vs-screen"><div class="vs-placeholder" id="vs-placeholder"><span>▷</span>你的视频将在这里呈现<p class="vs-muted">选择生成模式，填写内容后开始创作</p></div><video id="vs-player" controls preload="metadata" hidden></video></div><progress id="vs-progress" class="vs-progress" max="100" hidden></progress><p id="vs-result-message" class="vs-message" aria-live="polite"></p><div class="vs-actions"><button type="button" id="vs-refresh" disabled>刷新状态</button><button type="button" id="vs-download" disabled>下载视频</button><button type="button" id="vs-again" disabled>载入参数</button></div><h4 class="vs-history-title">最近生成</h4><div id="vs-history" class="vs-history"></div><p class="vs-notice" id="vs-empty">暂无记录，开始你的第一个视频创作。</p><p class="vs-muted">记录保存在本机，按登录账号隔离。切换页面不影响状态查询。</p></section></div>`;
 document.querySelector('.content').append(page);
 const $=id=>page.querySelector('#vs-'+id),names={text:'文生视频',frames:'首尾帧生视频',references:'多图参考生视频'},labels={queued:'排队中',running:'生成中',succeeded:'已完成',failed:'失败',cancelled:'已取消'};
 let mode='text',frames=[null,null],references=[],owner=null,epoch=0,records=[],selected=null,busy=false,inFlight=new Set();
 const key=()=> 'vimo-video-studio-v1:'+owner;
 function save(){if(!owner)return;try{localStorage.setItem(key(),JSON.stringify(records.slice(0,30)))}catch{$('form-message').textContent='本机存储空间不足，生成记录可能无法保存。'}}
 function errorText(e){return String(e.message||e).replace(/^Error invoking remote method.*?Error: /,'')}
 function updateSubmit(){ $('submit').disabled=busy||!owner;$('submit').textContent=busy?'正在提交…':'生成视频';}
 function setMode(value){mode=value;page.querySelectorAll('[data-mode]').forEach(b=>b.setAttribute('aria-selected',String(b.dataset.mode===mode)));$('material-section').hidden=mode==='text';$('swap').hidden=mode!=='frames';$('unavailable').hidden=mode!=='references';$('unavailable').textContent='支持 1–9 张参考图，总计不超过 30 MB。点击图片即可把 @参考图序号 插入提示词；图片越多，显存与耗时越高。';$('material-label').textContent=mode==='frames'?'首尾帧':'参考图片';$('form-message').textContent='';renderMaterials();updateSubmit();}
 page.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>setMode(b.dataset.mode));
 page.querySelector('.vs-tabs').onkeydown=e=>{if(!['ArrowLeft','ArrowRight'].includes(e.key))return;e.preventDefault();const list=['text','frames','references'];setMode(list[(list.indexOf(mode)+(e.key==='ArrowRight'?1:2))%3]);page.querySelector(`[data-mode="${mode}"]`).focus();};
 async function readImage(file){if(!file||!['image/png','image/jpeg','image/webp'].includes(file.type))throw Error('请选择 PNG、JPEG 或 WebP 图片');if(file.size>10*1024*1024)throw Error('单张图片不能超过 10 MB');const url=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=()=>reject(Error('图片读取失败'));r.readAsDataURL(file)});await new Promise((resolve,reject)=>{const i=new Image();i.onload=resolve;i.onerror=()=>reject(Error('图片无法解码'));i.src=url});return {kind:'image',title:file.name,url};}
 function insertReference(index){const prompt=$('prompt'),token=`@参考图${index+1}`,start=prompt.selectionStart??prompt.value.length,end=prompt.selectionEnd??start,before=prompt.value.slice(0,start),after=prompt.value.slice(end),left=before&&!/\s$/.test(before)?' ':'',right=after&&!/^\s/.test(after)?' ':'';prompt.value=before+left+token+right+after;const caret=before.length+left.length+token.length+right.length;prompt.focus();prompt.setSelectionRange(caret,caret);prompt.dispatchEvent(new Event('input',{bubbles:true}));}
 function remapReferences(map){const prompt=$('prompt');prompt.value=prompt.value.replace(/@参考图\s*(\d{1,2})/g,(token,n)=>map(Number(n))??token);prompt.dispatchEvent(new Event('input',{bubbles:true}));}
 function renderMaterials(){const root=$('materials');root.replaceChildren();if(mode==='text')return;const list=mode==='frames'?frames:[...references,null];list.forEach((item,index)=>{const card=document.createElement('div');card.className='vs-upload';const label=document.createElement('label');label.textContent=mode==='frames'?(index===0?'首帧':'尾帧'):item?`参考图 ${index+1}`:'添加参考图';card.append(label);if(item){const img=document.createElement('img');img.src=item.url;img.alt=mode==='references'?`参考图 ${index+1}，点击插入 @参考图${index+1}`:item.title;if(mode==='references'){img.className='vs-reference-image';img.tabIndex=0;img.setAttribute('role','button');img.title=`点击插入 @参考图${index+1}`;img.onclick=()=>insertReference(index);img.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();insertReference(index)}}}card.append(img);if(mode==='references'){const mention=document.createElement('button');mention.type='button';mention.className='vs-mention';mention.textContent=`@参考图${index+1}`;mention.title='插入到提示词';mention.onclick=()=>insertReference(index);card.append(mention)}}const input=document.createElement('input');input.type='file';input.accept='image/png,image/jpeg,image/webp';input.setAttribute('aria-label',label.textContent);card.append(input);
 const pick=async file=>{const ticket=epoch,target=mode;try{const image=await readImage(file);if(ticket!==epoch||target!==mode)return;if(mode==='frames')frames[index]=image;else{if(index>=9)throw Error('最多添加 9 张参考图片');const next=[...references];next[index]=image;if(next.reduce((n,r)=>n+(r.url.split(',')[1].length*3/4),0)>30*1024*1024)throw Error('参考图片总大小不得超过 30 MB');references=next;}renderMaterials();$('form-message').textContent='';}catch(e){if(ticket===epoch)$('form-message').textContent=errorText(e)}};
 input.onchange=()=>{if(input.files[0])void pick(input.files[0]);};card.ondragover=e=>e.preventDefault();card.ondrop=e=>{e.preventDefault();void pick(e.dataTransfer.files[0])};if(item){const remove=document.createElement('button');remove.type='button';remove.textContent='移除';remove.onclick=()=>{if(mode==='frames')frames[index]=null;else{references.splice(index,1);remapReferences(n=>n===index+1?'':n>index+1?`@参考图${n-1}`:null)}renderMaterials()};card.append(remove);if(mode==='references'&&index>0){const move=document.createElement('button');move.type='button';move.textContent='前移';move.onclick=()=>{[references[index-1],references[index]]=[references[index],references[index-1]];remapReferences(n=>n===index+1?`@参考图${index}`:n===index?`@参考图${index+1}`:null);renderMaterials()};card.append(move)}}root.append(card);});}
 $('swap').onclick=()=>{frames.reverse();renderMaterials()};
 function resetPlayer(){const player=$('player');player.pause();player.removeAttribute('src');player.load();player.hidden=true;$('placeholder').hidden=false;$('download').disabled=true;}
 function renderHistory(){const root=$('history');root.replaceChildren();$('empty').hidden=records.length>0;for(const row of records.slice(0,12)){const b=document.createElement('button');b.type='button';b.setAttribute('aria-pressed',String(row.id===selected));const title=document.createElement('strong');title.textContent=row.input.prompt;const meta=document.createElement('small');meta.textContent=`${names[row.mode]} · ${labels[row.status]||row.status}\n${row.input.duration} 秒 · ${row.input.resolution}`;b.append(title,meta);b.onclick=()=>select(row.id);root.append(b);}}
 function renderState(row){$('status').textContent=labels[row.status]||'查询中';$('result-message').textContent=row.error||row.stage||'';$('progress').hidden=!['queued','running'].includes(row.status);if(Number.isFinite(row.percent))$('progress').value=row.percent;else $('progress').removeAttribute('value');$('again').disabled=false;$('refresh').disabled=false;}
 async function select(id){selected=id;resetPlayer();renderHistory();const row=records.find(r=>r.id===id);if(!row)return;renderState(row);if(row.status==='succeeded'){const ticket=epoch;$('result-message').textContent='正在加载视频…';try{const result=await window.videoGeneration.download(id);if(ticket!==epoch||selected!==id)return;if(!result.url?.startsWith('file:'))throw Error('无效的视频地址');$('player').src=result.url;$('player').hidden=false;$('placeholder').hidden=true;$('download').disabled=false;$('result-message').textContent='生成完成，可以播放或下载。';}catch(e){if(ticket===epoch&&selected===id)$('result-message').textContent='视频加载失败，可点击记录重试：'+errorText(e)}}else void refresh(id);}
 async function refresh(id){if(!owner||inFlight.has(id))return;const row=records.find(r=>r.id===id);if(!row)return;const ticket=epoch;inFlight.add(id);if(selected===id)$('refresh').disabled=true;try{const state=await window.videoGeneration.status(id);if(ticket!==epoch)return;row.status=state.status;row.stage=state.progress?.stage||state.stage||'';row.percent=typeof state.progress==='number'?state.progress:state.progress?.percent;row.error=state.error?String(state.error):'';save();renderHistory();if(selected===id){renderState(row);if(row.status==='succeeded')void select(id)}}catch(e){if(ticket===epoch&&selected===id){$('status').textContent='状态待确认';$('result-message').textContent='状态查询超时，生成任务不受影响；可点“刷新状态”重试。'+errorText(e)}}finally{inFlight.delete(id);if(ticket===epoch&&selected===id)$('refresh').disabled=false}}
 function poll(){if(!owner)return;for(const row of records.filter(r=>['queued','running'].includes(r.status)))void refresh(row.id)}
 $('refresh').onclick=()=>{if(selected)void refresh(selected)};
 page.querySelector('form').onsubmit=async e=>{e.preventDefault();if(busy||!owner)return;const input={mode,prompt:$('prompt').value.trim(),duration:Number($('duration').value),resolution:$('resolution').value,aspectRatio:$('ratio').value,references:mode==='frames'?frames:mode==='references'?references:[]};if(!input.prompt){$('form-message').textContent='请填写提示词';return}if(mode==='references'&&!references.length){$('form-message').textContent='请上传至少一张参考图片';return}if(mode==='frames'&&frames.some(x=>!x)){$('form-message').textContent='请上传首帧和尾帧图片';return}busy=true;updateSubmit();const ticket=epoch;$('form-message').textContent='正在检查服务并提交，请勿重复操作…';try{const result=await window.videoGeneration.submit(input);if(ticket!==epoch)return;const {references:ignored,...parameters}=input;records.unshift({id:result.id,status:result.status||'queued',mode:input.mode,input:parameters});records=records.slice(0,30);save();void select(result.id);$('form-message').textContent='任务已提交。可以切换页面，稍后回来查看。';void poll();}catch(e){if(ticket===epoch)$('form-message').textContent=errorText(e)}finally{if(ticket===epoch){busy=false;updateSubmit()}}};
 $('again').onclick=()=>{const row=records.find(r=>r.id===selected);if(!row)return;setMode(row.mode);$('prompt').value=row.input.prompt;$('duration').value=row.input.duration;$('ratio').value=row.input.aspectRatio;$('resolution').value=row.input.resolution;if(row.mode!=='text'){frames=[null,null];references=[];renderMaterials();$('form-message').textContent='参数已载入，请重新上传生成素材。'}else $('form-message').textContent='参数已载入，点击生成视频后提交。';};
 $('download').onclick=async()=>{const id=selected,ticket=epoch;$('download').disabled=true;try{await window.videoGeneration.export(id)}catch(e){if(ticket===epoch)$('result-message').textContent='下载失败：'+errorText(e)}finally{if(ticket===epoch&&selected===id)$('download').disabled=false}};
 window.addEventListener('account-locked',()=>{epoch++;owner=null;records=[];selected=null;busy=false;inFlight.clear();frames=[null,null];references=[];$('prompt').value='';resetPlayer();renderHistory();$('status').textContent='等待生成';$('result-message').textContent='';$('form-message').textContent='';$('again').disabled=true;$('refresh').disabled=true;$('progress').hidden=true;setMode('text');});
 window.addEventListener('account-ready',e=>{owner=e.detail?.id;if(!owner)return;try{const data=JSON.parse(localStorage.getItem(key())||'[]');records=Array.isArray(data)?data.filter(r=>/^video_[a-f0-9]{32}$/.test(r.id)&&names[r.mode]&&typeof r.input?.prompt==='string').slice(0,30):[]}catch{records=[]}updateSubmit();renderHistory();if(records[0])void select(records[0].id);void poll();});
 setInterval(poll,5000);window.addEventListener('focus',poll);document.addEventListener('visibilitychange',()=>{if(!document.hidden)poll()});setMode('text');
})();
